name: electron-snap-test
version: '1.0.0'
summary: App summary
description: |
  App description

grade: stable
confinement: classic

apps:
  electron-snap-test:
    command:
      '$SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin'
    plugs:
    - browser-support
    - desktop
    - desktop-legacy
    - gsettings
    - home
    - mount-observe
    - network
    - network-bind
    - unity7
    - x11
    environment:
      TMPDIR: $XDG_RUNTIME_DIR

parts:
  electron-snap-test:
    source: .
    plugin: dump
    stage-packages:
    - libnotify4
    - libnss3
    - libpcre3
    - libxss1
    - libxtst6
    after:
    - desktop-gtk2